model_name: all_structures_flexray_v4
labels:
  - background
  - skull
  - scapulae
  - clavicles
  - humeri
  - phalanges
  - metacarpals
  - carpals
  - radii
  - ulnae
  - tibiae
  - femurs
  - patellae
  - fibulae
  - metatarsals
  - tarsals
  - toes
  - rib_1
  - rib_2
  - rib_3
  - rib_4
  - rib_5
  - rib_6
  - rib_7
  - rib_8
  - rib_9
  - rib_10
  - rib_11
  - rib_12
  - sternum
  - vertebra_c1
  - vertebra_c2
  - vertebra_c3
  - vertebra_c4
  - vertebra_c5
  - vertebra_c6
  - vertebra_c7
  - vertebra_t1
  - vertebra_t2
  - vertebra_t3
  - vertebra_t4
  - vertebra_t5
  - vertebra_t6
  - vertebra_t7
  - vertebra_t8
  - vertebra_t9
  - vertebra_t10
  - vertebra_t11
  - vertebra_t12
  - vertebra_l1
  - vertebra_l2
  - vertebra_l3
  - vertebra_l4
  - vertebra_l5
  - hips
  - sacrum
  - kidneys
  - liver
  - spleen
  - lungs
  - heart
