dataset_name: HANSeg
skip_subjects: null
stored_labels:
  0: background
  1: carpal_left
  2: carpal_right
  3: clavicle_left
  4: clavicle_right
  5: femur_left
  6: femur_right
  7: fibula_left
  8: fibula_right
  9: phalange_left
  10: phalange_right
  11: humerus_left
  12: humerus_right
  13: metacarpal_left
  14: metacarpal_right
  15: metatarsal_left
  16: metatarsal_right
  17: patella_left
  18: patella_right
  19: radius_left
  20: radius_right
  21: scapula_left
  22: scapula_right
  23: skull
  24: tarsal_left
  25: tarsal_right
  26: tibia_left
  27: tibia_right
  28: toe_left
  29: toe_right
  30: ulna_left
  31: ulna_right
  32: rib_left_1
  33: rib_left_2
  34: rib_left_3
  35: rib_left_4
  36: rib_left_5
  37: rib_left_6
  38: rib_left_7
  39: rib_left_8
  40: rib_left_9
  41: rib_left_10
  42: rib_left_11
  43: rib_left_12
  44: rib_left_13
  45: rib_right_1
  46: rib_right_2
  47: rib_right_3
  48: rib_right_4
  49: rib_right_5
  50: rib_right_6
  51: rib_right_7
  52: rib_right_8
  53: rib_right_9
  54: rib_right_10
  55: rib_right_11
  56: rib_right_12
  57: rib_right_13
  58: sternum
  59: vertebra_c1
  60: vertebra_c2
  61: vertebra_c3
  62: vertebra_c4
  63: vertebra_c5
  64: vertebra_c6
  65: vertebra_c7
  66: vertebra_t1
  67: vertebra_t2
  68: vertebra_t3
  69: vertebra_t4
  70: vertebra_t5
  71: vertebra_t6
  72: vertebra_t7
  73: vertebra_t8
  74: vertebra_t9
  75: vertebra_t10
  76: vertebra_t11
  77: vertebra_t12
  78: vertebra_l1
  79: vertebra_l2
  80: vertebra_l3
  81: vertebra_l4
  82: vertebra_l5
  83: vertebra_l6
  84: hip_left
  85: hip_right
  86: sacrum
  87: adrenal_gland_left
  88: adrenal_gland_right
  89: bladder
  90: brain
  91: gallbladder
  92: kidney_left
  93: kidney_right
  94: liver
  95: lung_lower_lobe_left
  96: lung_lower_lobe_right
  97: lung_middle_lobe_right
  98: lung_upper_lobe_left
  99: lung_upper_lobe_right
  100: pancreas
  101: spleen
  102: stomach
  103: thyroid_left
  104: thyroid_right
  105: heart_myocardium
  106: heart_atrium_left
  107: heart_atrium_right
  108: heart_ventricle_left
  109: heart_ventricle_right
  110: aorta
  111: iliac_artery_left
  112: iliac_artery_right
  113: iliac_vena_left
  114: iliac_vena_right
  115: inferior_vena_cava
  116: portal_splenic_vein
  117: pulmonary_artery
protocol_label_aliases:
  all_structures_flexray_v4:
    carpal_left: carpals
    carpal_right: carpals
    clavicle_left: clavicles
    clavicle_right: clavicles
    femur_left: femurs
    femur_right: femurs
    fibula_left: fibulae
    fibula_right: fibulae
    phalange_left: phalanges
    phalange_right: phalanges
    humerus_left: humeri
    humerus_right: humeri
    metacarpal_left: metacarpals
    metacarpal_right: metacarpals
    metatarsal_left: metatarsals
    metatarsal_right: metatarsals
    patella_left: patellae
    patella_right: patellae
    radius_left: radii
    radius_right: radii
    scapula_left: scapulae
    scapula_right: scapulae
    tarsal_left: tarsals
    tarsal_right: tarsals
    tibia_left: tibiae
    tibia_right: tibiae
    toe_left: toes
    toe_right: toes
    ulna_left: ulnae
    ulna_right: ulnae
    rib_left_1: rib_1
    rib_left_2: rib_2
    rib_left_3: rib_3
    rib_left_4: rib_4
    rib_left_5: rib_5
    rib_left_6: rib_6
    rib_left_7: rib_7
    rib_left_8: rib_8
    rib_left_9: rib_9
    rib_left_10: rib_10
    rib_left_11: rib_11
    rib_left_12: rib_12
    rib_right_1: rib_1
    rib_right_2: rib_2
    rib_right_3: rib_3
    rib_right_4: rib_4
    rib_right_5: rib_5
    rib_right_6: rib_6
    rib_right_7: rib_7
    rib_right_8: rib_8
    rib_right_9: rib_9
    rib_right_10: rib_10
    rib_right_11: rib_11
    rib_right_12: rib_12
    hip_left: hips
    hip_right: hips
    kidney_left: kidneys
    kidney_right: kidneys
    lung_lower_lobe_left: lungs
    lung_lower_lobe_right: lungs
    lung_middle_lobe_right: lungs
    lung_upper_lobe_left: lungs
    lung_upper_lobe_right: lungs
    heart_myocardium: heart
    heart_atrium_left: heart
    heart_atrium_right: heart
    heart_ventricle_left: heart
    heart_ventricle_right: heart
protocol_drop_labels:
  all_structures_flexray_v4:
  - rib_left_13
  - rib_right_13
  - vertebra_l6
  - adrenal_gland_left
  - adrenal_gland_right
  - bladder
  - brain
  - gallbladder
  - pancreas
  - stomach
  - thyroid_left
  - thyroid_right
  - aorta
  - iliac_artery_left
  - iliac_artery_right
  - iliac_vena_left
  - iliac_vena_right
  - inferior_vena_cava
  - portal_splenic_vein
  - pulmonary_artery
